### ISSUE TITLE
"Order is not defined" error

### ISSUE THREAD

**Issue by Kethuel** [scryfall/google-sheets#1]
This was giving an error that 'Order' was not defined (line 56). It works after decapitalising the 'Order's on that line, though.

**Comment by april** [comment]
Hmm, looking at line 56, I see:

`order = order_mappings[order] === undefined ? order : order_mappings[order];`

Where did you see a capitalized order?

**Comment by Kethuel** [comment]
Whoops, problem was on my end. I had the AutocardAnywhere chrome extension enabled, which lets you hover over cardnames to see the cards, and was picking it up as the Order part of Order//Chaos. It also happens to capitalise them for whatever reason. Gah. Thanks for the help, apologies for the inconvenience.
