### ISSUE TITLE
Turn off Unique parameter

### ISSUE THREAD

**Issue by bananahead4** [scryfall/google-sheets#16]
Hello, is there a way to turn off the only unique card parameter in =SCRYFALL() function that is on by default? 

I've filled in the entire function [SCRYFALL(query, fields, num_results, order, dir, unique)] but cant figure out what goes in the unique slot to let it call upon the same card when it shows up multiple times in a set.

**Comment by bananahead4** [comment]
The line I have been using is the following:

=SCRYFALL("is:boosterfun set:UNF comet", "name collector_number colors prices.usd prices.usd_foil, card", 750, "price", "desc", FALSE)

This search should turn up 3 version of the card but is only showing one. I have tried change the FALSE to TRUE, 0, 1 and a few other strings to try and turn off the unique filter.

**Comment by april** [comment]
It behaves like Scryfall does, so you can add `unique:prints` and it should work.
